# CS-160-02 - Project #1 - Working With Numpy

## Gracie Bayer - January 26, 2021

In [2]:
import numpy as np
print(np.__version__)

1.20.1


### `a. 2-by-2 NumPy array with elements 10, 20, 30, 40`

In [3]:
arr1=np.array([[10,20],[30,40]])
print(arr1)

[[10 20]
 [30 40]]


#### i. Square every element of the array

In [4]:
np.square(arr1)

array([[ 100,  400],
       [ 900, 1600]])

#### ii. Add 100 to every element of the array

In [5]:
np.add(arr1,100)

array([[110, 120],
       [130, 140]])

#### iii. Multiply every element of the array by 5

In [6]:
np.multiply(arr1,5)

array([[ 50, 100],
       [150, 200]])

#### iv. Calculate the square root of each element in the array

In [7]:
np.sqrt(arr1)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

### `b. 3-by-3 array containing integers from 3 to 27 in multiples of 3; 3-by-3 array with 9 elements evenly spaced between 10 and 20; multiply these arrays together`

In [8]:
arr2=np.array(range(3,28,3)).reshape(3,3)
print(arr2)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [53]:
arr3=np.linspace(10,20,9).reshape(3,3)
print(arr3)

[[10.   11.25 12.5 ]
 [13.75 15.   16.25]
 [17.5  18.75 20.  ]]


In [54]:
np.multiply(arr2,arr3)

array([[ 30. ,  67.5, 112.5],
       [165. , 225. , 292.5],
       [367.5, 450. , 540. ]])

### `c. 5-by-5 NumPy array; calculate the mean of each column of data`

In [35]:
process1=np.load('process1.npy')

In [36]:
process1

array([[52, 12, 81,  0, 58]], dtype=int32)

In [40]:
process1.mean()

40.6

In [41]:
process2=np.load('process2.npy')

In [42]:
process2

array([[96,  4, 61, 16, 43]], dtype=int32)

In [43]:
process2.mean()

44.0

In [44]:
process3=np.load('process3.npy')

In [45]:
process3

array([[38, 96, 45, 17, 58]], dtype=int32)

In [46]:
process3.mean()

50.8

In [47]:
process4=np.load('process4.npy')

In [48]:
process4

array([[97, 21, 22, 25,  6]], dtype=int32)

In [49]:
process4.mean()

34.2

In [50]:
process5=np.load('process5.npy')

In [51]:
process5

array([[77,  6, 19,  2, 74]], dtype=int32)

In [52]:
process5.mean()

35.6